# Generated by Django 5.2.6 on 2025-09-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_customuser_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citoyenprofile',
            name='telephone',
        ),
        migrations.AddField(
            model_name='citoyenprofile',
            name='isValid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='citoyenprofile',
            name='cin',
            field=models.ImageField(blank=True, default='cins/default_cin.png', null=True, upload_to='cins/'),
        ),
    ]
