# Generated by Django 5.0.6 on 2025-09-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_remove_citoyenprofile_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('citoyen', 'Citoyen'), ('agent', 'Agent'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
