# Generated by Django 5.0.6 on 2025-09-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='serviceCategory',
            field=models.CharField(choices=[('LIGHT', 'Éclairage Public'), ('ROAD', 'Routes & Trottoirs'), ('WATER', 'Eau & Assainissement'), ('SANITATION', 'Gestion des Déchets & Propreté'), ('ELECTRICITY', 'Infrastructures Électriques'), ('TELECOM', 'Lignes de Télécommunication'), ('TRAFFIC', 'Feux & Signalisation Routière'), ('BUILDING', 'Entretien des Bâtiments Publics'), ('PARK', 'Parcs & Espaces Verts'), ('BRIDGE', 'Ponts & Passerelles'), ('EMERGENCY', 'Réparations d’Urgence'), ('ALL', 'Tous Services')], default='ALL', max_length=30),
        ),
    ]
