# Generated by Django 5.0.6 on 2025-09-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_agentprofile_servicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='plain_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
