# Generated by Django 5.0.6 on 2025-09-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0003_remove_citoyenprofile_telephone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('infrastructures_critiques', 'Infrastructures critiques'), ('environnement_proprete', 'Environnement et propreté'), ('energie_electricite', 'Énergie et électricité'), ('assainissement_eau', 'Assainissement et eau'), ('transport_stationnement', 'Transport et stationnement'), ('trottoirs_mobilite_douce', 'Trottoirs et mobilité douce'), ('voirie_routes', 'Voirie et routes'), ('eclairage_public', 'Éclairage public')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('resolved', 'Résolu')], default='pending', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_misajour', models.DateTimeField(default=models.DateTimeField(auto_now_add=True))),
                ('localization', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='problems/')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_reclamations', to='userauth.agentprofile')),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reclamations', to='userauth.citoyenprofile')),
            ],
        ),
    ]
