# Generated by Django 5.0.6 on 2025-09-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='validate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='category',
            field=models.CharField(choices=[('infrastructures critiques', 'Infrastructures critiques'), ('environnement proprete', 'Environnement et propreté'), ('energie electricite', 'Énergie et électricité'), ('assainissement eau', 'Assainissement et eau'), ('transport stationnement', 'Transport et stationnement'), ('trottoirs mobilite douce', 'Trottoirs et mobilité douce'), ('voirie routes', 'Voirie et routes'), ('eclairage public', 'Éclairage public')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date_misajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Résolu', 'Résolu')], default='En attente', max_length=20),
        ),
    ]
